FROM golang:1.25-alpine

# Устанавливаем компилятор C для CGO
RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Включаем CGO explicitly
ENV CGO_ENABLED=1

RUN go build -o receiver ./cmd/receiver

CMD ["./receiver"]